#!/usr/bin/env bash

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/dotfiles-nixos"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Current theme ---------------------------------------------#

## Bspwm colors
BSPWM_FBC='#007B82'
BSPWM_NBC='#01161b'
BSPWM_ABC='#05bbc5'
BSPWM_PFC='#028c94'

## Bspwm appearance
BSPWM_BORDER='1'
BSPWM_GAP='10'
BSPWM_SRATIO='0.50'

## Configurations --------------------------------------------#

## Set Display alignment
 xrandr --output HDMI-1 --pos 0x500 --rotation normal --output DP-2 --pos 1920x0 --primary --rotation normal

## Set  Workspaces
workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		if (( $name==1 )) ; then
			bspc monitor ${monitor} -n "$name" -d '1' '2' '3'
		else
			bspc monitor ${monitor} -n "$name" -d 'Q' 'W' 'E'
		fi
		let name++
	done
	#bspc monitor DP-2 -n "2" -d '' '' '' '' '' '' '' ''
}
workspaces

## Apply bspwm configurations
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans


## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey bspc

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash .fehbg

# Start bspwm scripts
bspbar
bspcomp
bspdunst
bspfloat &
